// Real, central SHAKTHI_OS version identity -- section 45 of the founder's
// Executive Neural Network spec. Every field here is real: the version
// number is the one the founder himself confirmed tonight (see
// project_shakthi_os_versioning memory); the commit is the real last-known
// git HEAD at build time. No fabricated build numbers, no fake CI metadata
// this project doesn't have.

export const SHAKTHI_OS_VERSION = {
  osName: "SHAKTHI_OS",
  version: "3.2.0",
  codename: "Revenue Mission Engine",
  // Source snapshot commit copied from the SSD on 2026-09-04. This is
  // hand-set, not auto-generated by a build pipeline -- this project has
  // no CI that stamps commits into the bundle. Update by hand (or wire a
  // real build-time git-rev-parse step later) when it matters again.
  gitCommit: "338d30a",
  // Honest: nothing has been committed to git since this commit -- see the
  // standing "never commit unless the founder asks" rule. The running
  // dashboard may include real, uncommitted local changes not reflected
  // in this commit hash.
  environment: "local-dev" as const,
  releaseChannel: "stable" as const,
} as const;

export type ShakthiOsVersion = typeof SHAKTHI_OS_VERSION;
