import { getFailureAnalyses } from "@/lib/api";
import { Card, CardHeader, CardBody, Badge, EmptyState } from "@/components/ui";
import { AutoRefresh } from "@/components/AutoRefresh";

export const dynamic = "force-dynamic";

const SEVERITY_TONE: Record<string, "bad" | "warn" | "neutral"> = {
  P0: "bad", P1: "bad", P2: "warn", P3: "neutral", P4: "neutral",
};

export default async function FailureAnalysesPage() {
  const result = await getFailureAnalyses().catch(() => null);

  if (!result) {
    return (
      <Card>
        <CardHeader title="API unreachable" />
        <CardBody>
          <p className="text-sm text-[var(--muted-foreground)]">
            Could not reach the Shakthi API. Start it with{" "}
            <code className="text-[var(--ink)]">python3 -m orchestrator.api</code> in the shakthi-os directory, then reload.
          </p>
        </CardBody>
      </Card>
    );
  }

  const analyses = result.analyses;

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-xl font-semibold">Failure Analysis Engine</h1>
          <p className="text-sm text-[var(--muted-foreground)] mt-1">
            Task 4 — scoped down from a full Six Sigma/DMAIC framework to one real, high-leverage piece: a genuine
            5-Whys root-cause record per real failure, so the same one doesn&apos;t happen twice. Written by hand from
            real investigation, not auto-generated by a model — see the note on{" "}
            <code>orchestrator/failure_analysis.py</code>.
          </p>
        </div>
        <AutoRefresh intervalSeconds={5} />
      </div>

      {analyses.length === 0 ? (
        <Card>
          <CardBody>
            <EmptyState>
              No failure analyses recorded yet. Use <code>--failure-analysis-add &lt;json_path&gt;</code> from the CLI.
            </EmptyState>
          </CardBody>
        </Card>
      ) : (
        <div className="space-y-4">
          {analyses.map((a) => (
            <Card key={a.id}>
              <CardHeader
                title={`#${a.id} — ${a.title}`}
                subtitle={`${a.source_type}${a.source_id ? ` #${a.source_id}` : ""} · ${a.created_at}`}
                action={
                  <div className="flex items-center gap-2">
                    <Badge tone={SEVERITY_TONE[a.severity] ?? "neutral"}>{a.severity}</Badge>
                    <Badge tone={a.status === "closed" ? "good" : "warn"}>{a.status}</Badge>
                  </div>
                }
              />
              <CardBody className="space-y-4">
                <p className="text-sm text-[var(--ink)] leading-relaxed">{a.summary}</p>

                <div>
                  <div className="text-[11px] uppercase tracking-wide text-[var(--muted-foreground)] mb-1.5">5 Whys</div>
                  <ol className="space-y-1.5 list-decimal list-inside">
                    {a.five_whys.map((w, i) => (
                      <li key={i} className="text-sm text-[var(--muted-foreground)] leading-relaxed">{w}</li>
                    ))}
                  </ol>
                </div>

                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  <div>
                    <div className="text-[11px] uppercase tracking-wide text-[var(--muted-foreground)] mb-1">Root Cause</div>
                    <p className="text-sm text-[var(--ink)] leading-relaxed">{a.root_cause}</p>
                  </div>
                  <div>
                    <div className="text-[11px] uppercase tracking-wide text-[var(--muted-foreground)] mb-1">Corrective Action</div>
                    <p className="text-sm text-[var(--ink)] leading-relaxed">{a.corrective_action}</p>
                  </div>
                  <div>
                    <div className="text-[11px] uppercase tracking-wide text-[var(--good)] mb-1">Preventive Action (Poka-Yoke)</div>
                    <p className="text-sm text-[var(--ink)] leading-relaxed">{a.preventive_action}</p>
                  </div>
                  <div>
                    <div className="text-[11px] uppercase tracking-wide text-[var(--muted-foreground)] mb-1">Lessons Learned</div>
                    <p className="text-sm text-[var(--ink)] leading-relaxed">{a.lessons_learned}</p>
                  </div>
                </div>
              </CardBody>
            </Card>
          ))}
        </div>
      )}
    </div>
  );
}
