"use client";
import { PointerEvent, useRef, useState } from "react";

export function WorkspaceScene() {
  const ref = useRef<HTMLDivElement>(null); const [paused, setPaused] = useState(false);
  const tilt = (event: PointerEvent<HTMLDivElement>) => { if (paused || window.matchMedia("(prefers-reduced-motion: reduce)").matches || !ref.current) return; const box = ref.current.getBoundingClientRect(); ref.current.style.setProperty("--tilt-x", `${((event.clientY - box.top) / box.height - .5) * -5}deg`); ref.current.style.setProperty("--tilt-y", `${((event.clientX - box.left) / box.width - .5) * 7}deg`); };
  const reset = () => { if (ref.current) { ref.current.style.setProperty("--tilt-x", "0deg"); ref.current.style.setProperty("--tilt-y", "0deg"); } };
  return <div className={`dh-scene-wrap ${paused ? "dh-paused" : ""}`}><div className="dh-scene" ref={ref} onPointerMove={tilt} onPointerLeave={reset} aria-label="Illustrated DhanSetu workspace preview"><div className="dh-orbit orbit-one" /><div className="dh-orbit orbit-two" /><div className="dh-sphere" /><div className="dh-workspace"><div className="dh-workspace-side"><b>d↗</b><i>▦</i><i>◒</i><i>▤</i><i>⚙</i></div><div className="dh-workspace-main"><span className="dh-scene-label">YOUR PERSONAL WORKSPACE</span><div className="dh-scene-top"><h3>A little more<br /><em>clarity.</em></h3><span className="dh-scene-avatar">DS</span></div><div className="dh-balance"><small>SMARTBUDGET · ILLUSTRATIVE BALANCE</small><strong>₹42,850</strong><div className="dh-bars">{[36,55,42,72,58,87,69,95,77,100,88,112].map((height, index) => <i key={index} style={{ height: `${height}%`, animationDelay: `${index * 70}ms` }} />)}</div></div><div className="dh-scene-bottom"><span>Essentials <b>₹18,400</b></span><span>Your goals <b>₹12,200</b></span><span>Everything else <b>₹12,250</b></span></div></div></div><div className="dh-float-card dh-doc-card"><b>▧</b><span>Less paperwork.<br /><em>More possibilities.</em></span></div><div className="dh-float-card dh-idea-card"><small>YOUR NEXT BIG IDEA</small><b>It starts with a<br /><em>little spark.</em></b><i>✦</i></div><div className="dh-private-card"><span>✦</span><div><b>Your files. Your device.</b><small>Local document processing</small></div></div><div className="dh-sparkle sparkle-one">✦</div><div className="dh-sparkle sparkle-two">✦</div></div><button className="dh-scene-pause" type="button" onClick={() => setPaused((value) => !value)} aria-pressed={paused}>{paused ? "Play motion" : "Pause motion"} · {paused ? "▶" : "Ⅱ"}</button><p className="dh-scene-caption">WORKSPACE PREVIEW · SAMPLE DATA</p></div>;
}
