import Link from "next/link";
import { TIERS } from "@/lib/payment/tiers";
import { WorkspaceScene } from "@/components/home/WorkspaceScene";
import "./home.css";

const tools = [
  ["SmartBudget", "See where your money is really going.", "/smartbudget", "₹", "mint"],
  ["Image to PDF", "Turn everyday documents into share-ready files.", "/tools/image-to-pdf", "▧", "blue"],
  ["Invoice Studio", "Create a clean invoice in a few calm clicks.", "/tools/invoice", "↗", "peach"],
] as const;

export default function Home() {
  return <main className="dh-home">
    <a className="dh-skip" href="#workspace">Skip to workspace</a>
    <header className="dh-nav dh-shell"><Link href="/" className="dh-brand"><span className="dh-brand-mark">d↗</span><span><b>dhansetu</b><small>YOUR EVERYDAY ADVANTAGE</small></span></Link><nav className="dh-desktop-nav"><a href="#workspace">Workspace</a><a href="#how">How it works</a><a href="#pricing">Pricing</a></nav><Link href="/login" className="dh-login">Sign in <span>↗</span></Link></header>
    <section id="workspace" className="dh-hero dh-shell"><div className="dh-hero-copy"><p className="dh-eyebrow">A LITTLE CLARITY. A LOT MORE POSSIBILITY.</p><h1>Your life.<br />Less busy.<br /><em>More brilliant.</em></h1><p className="dh-lead">A thoughtful home for your money, documents, and next big idea. Make room for the work—and life—that matters.</p><div className="dh-actions"><a href="#tools" className="dh-button dh-button-primary">Explore the workspace <span>↗</span></a><Link href="/smartbudget" className="dh-button dh-button-quiet">Open SmartBudget</Link></div><div className="dh-proof"><span>✦ Browser-based tools</span><span>✦ Built for everyday India</span></div></div><WorkspaceScene /><div className="dh-hero-note"><span>01 / 04</span><span>DESIGNED FOR THE<br />MOMENTS IN BETWEEN</span></div></section>
    <div className="dh-ribbon"><span>ONE HUB. MANY POSSIBILITIES.</span><span>Money clarity <i>✦</i></span><span>Everyday documents <i>✦</i></span><span>Your next idea <i>✦</i></span></div>
    <section id="tools" className="dh-section dh-shell"><div className="dh-section-heading"><div><p className="dh-eyebrow">THE WORKSPACE</p><h2>Big little tools.<br /><em>Real-life possibilities.</em></h2></div><p>Useful things for the things you do every day. Private by design, quietly powerful by nature.</p></div><div className="dh-tool-grid">{tools.map(([title, text, href, icon, tone]) => <Link href={href} className={`dh-tool-card ${tone}`} key={title}><span className="dh-tool-icon">{icon}</span><span className="dh-tool-arrow">↗</span><h3>{title}</h3><p>{text}</p><span className="dh-tool-link">Open tool <b>→</b></span></Link>)}</div></section>
    <section id="how" className="dh-how dh-shell"><div><p className="dh-eyebrow">A BETTER WAY FORWARD</p><h2>A calmer way<br /><em>to get there.</em></h2></div><div className="dh-steps"><div><b>01</b><h3>Find your focus</h3><p>Start with the one thing that would make today feel lighter.</p></div><div><b>02</b><h3>Make it your own</h3><p>Your files stay close. Your workflow stays wonderfully yours.</p></div><div><b>03</b><h3>Move forward</h3><p>Small wins compound into the life you meant to build.</p></div></div></section>
    <section className="dh-idea dh-shell"><div><p className="dh-eyebrow">THE IDEA LAB</p><h2>That idea in your head?<br /><em>Give it a first step.</em></h2><p>Describe what you are thinking. Get a clear, practical starting point in seconds.</p></div><form action="/tools" method="get"><label htmlFor="idea">YOUR NEXT BIG IDEA</label><textarea id="idea" name="idea" required maxLength={1000} rows={3} placeholder="I want to build an AI service that..."></textarea><button className="dh-button dh-button-primary" type="submit">Explore my idea <span>↗</span></button><small>A starting point, not a promise. Always make the final call yourself.</small></form></section>
    <section id="pricing" className="dh-pricing dh-shell"><div className="dh-section-heading"><div><p className="dh-eyebrow">MAKE IT YOURS</p><h2>One good decision<br /><em>can change a lot.</em></h2></div><p>Choose the workspace that fits your next chapter. One payment, account-based access.</p></div><div className="dh-price-grid">{Object.entries(TIERS).map(([id, tier], index) => <article className={`dh-price-card ${index === 1 ? "featured" : ""}`} key={id}>{index === 1 && <span className="dh-price-tag">MOST POPULAR</span>}<p className="dh-price-kicker">{index === 0 ? "A STARTING POINT" : index === 1 ? "FOR BIGGER AMBITIONS" : "FOR THE FULL PICTURE"}</p><h3>{tier.label}</h3><strong>₹{(tier.amountPaise / 100).toLocaleString("en-IN")}</strong><span className="dh-price-one">ONE-TIME · LIFETIME ACCESS</span><ul><li>✓ One personal account</li><li>✓ Secure Razorpay checkout</li><li>✓ Purchase history and receipt</li></ul><Link href={`/checkout?tier=${id}`} className="dh-price-button">Get lifetime access <span>↗</span></Link><p className="dh-legal">By purchasing you agree to our <Link href="/terms">Terms</Link>, <Link href="/privacy">Privacy</Link> and <Link href="/refund">Refund Policy</Link>.</p></article>)}</div></section>
    <section className="dh-end dh-shell"><span className="dh-end-orb">✦</span><p className="dh-eyebrow">YOUR NEXT CHAPTER STARTS HERE</p><h2>Make space for<br /><em>what’s next.</em></h2><a href="#workspace" className="dh-button dh-button-primary">Enter your workspace <span>↗</span></a></section>
  </main>;
}
