"use client";

import { useState } from "react";
import Link from "next/link";
import { SUPPORT_EMAIL } from "@/lib/brand";

// Real pricing decision, 2026-08-24 -- founder's own call, delegated to
// CEO/market judgment: "take whatever's running in market, take average
// than low cost, because we are new." Grounded in a real search (AI
// agent/ops SaaS for small businesses/agencies, 2026): narrow single-
// workflow bots start near $0-50/mo, but agency-deployed multi-workflow
// agent teams run $300-1,500/mo per client in the US market. That US
// figure is the wrong comparable to import directly -- it prices out the
// actual target buyer here (small Indian agencies, per this page's own
// "for small agencies" framing), not enterprise. Landed on a real number
// roughly 2-3x the old placeholder -- fair-market, not bargain-bin, but
// not mismatched to who's actually buying. No longer a placeholder.
const TIERS = [
  { id: "blackboxops_os_starter", name: "Starter", price: 6999, period: "/month", desc: "Core agent team — CEO, Sentinel, Security, Finance — for one business." },
  { id: "blackboxops_os_growth", name: "Growth", price: 17999, period: "/month", desc: "Everything in Starter, plus Chrome Developer, Website Builder, Worker Pool, and ERT." },
];

// Real, live PayU checkout link, created directly in the founder's own
// PayU merchant dashboard -- not generated by this codebase's dynamic
// hash-based integration (payment_gateway_manager.py), which still needs
// real merchant key+salt env vars that haven't been provided yet. Fixed
// amount, so it's shown as its own real "Pay Now" action rather than
// stapled onto a Starter/Growth tier card whose price it may not match.
const REAL_PAYU_LINK = "https://u.payu.in/xJYCpF9eG4sc";

export default function BlackboxPricingPage() {
  const [gateway, setGateway] = useState<"razorpay" | "payu">("payu");
  const [email, setEmail] = useState("");
  const [razorpayKeyId, setRazorpayKeyId] = useState("");
  const [razorpaySecret, setRazorpaySecret] = useState("");
  const [payuKey, setPayuKey] = useState("");
  const [payuSalt, setPayuSalt] = useState("");
  const [status, setStatus] = useState<"idle" | "loading" | "error">("idle");
  const [error, setError] = useState("");
  const [result, setResult] = useState<{ checkout?: string | { action_url: string; fields: Record<string, string> } } | null>(null);

  async function subscribe(product: string) {
    if (!email) { setError("Enter an email first."); setStatus("error"); return; }
    setStatus("loading"); setError(""); setResult(null);
    try {
      const res = await fetch("/api/blackboxops/subscribe", {
        method: "POST", headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ email, product, gateway, razorpayKeyId, razorpaySecret, payuKey, payuSalt }),
      });
      const data = await res.json();
      if (!res.ok) throw new Error(data.error || "Failed");
      setResult(data);
      setStatus("idle");
    } catch (e) {
      setError(e instanceof Error ? e.message : "Something went wrong.");
      setStatus("error");
    }
  }

  return (
    <div className="fixed inset-0 overflow-y-auto" style={{ background: "#0a0c10", color: "#e8ecf1" }}>
      <div className="max-w-4xl mx-auto px-8 py-10">
        <Link href="/blackboxops-os" className="text-xs font-mono text-[#8b95a6] hover:text-white">← blackboxOps_OS</Link>
        <h1 className="text-3xl font-semibold mt-4 mb-2">Pricing</h1>
        <p className="text-sm text-[#a8b1c2] mb-2">
          Real launch pricing, set 2026-08-24 — priced at fair market value for a small agency, not bargain-bin,
          since we&apos;re new here and want to be trusted, not just cheap.
        </p>

        <div className="rounded-xl border p-6 my-8 flex items-center justify-between gap-6" style={{ borderColor: "#4ade8055", background: "#0f131a" }}>
          <div>
            <div className="flex items-center gap-2 mb-1.5">
              <span className="w-1.5 h-1.5 rounded-full" style={{ background: "#4ade80" }} />
              <span className="text-xs font-mono uppercase tracking-wide" style={{ color: "#4ade80" }}>Live · Real PayU checkout</span>
            </div>
            <div className="text-lg font-semibold">Pay Now</div>
            <p className="text-sm text-[#a8b1c2] mt-1">Real payment link, not a demo — opens the actual PayU checkout.</p>
          </div>
          <a
            href={REAL_PAYU_LINK}
            target="_blank"
            rel="noreferrer"
            className="shrink-0 rounded-lg px-6 py-3 text-sm font-semibold"
            style={{ background: "#4ade80", color: "#0a0c10" }}
          >
            Pay Now →
          </a>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-5 my-8">
          {TIERS.map((t) => (
            <div key={t.id} className="rounded-xl border border-[#1e232e] p-6" style={{ background: "#0f131a" }}>
              <div className="text-lg font-semibold">{t.name}</div>
              <div className="mt-2 mb-3">
                <span className="text-3xl font-semibold">₹{t.price.toLocaleString("en-IN")}</span>
                <span className="text-sm text-[#8b95a6]">{t.period}</span>
              </div>
              <p className="text-sm text-[#a8b1c2] mb-5">{t.desc}</p>
              <button
                onClick={() => subscribe(t.id)}
                disabled={status === "loading"}
                className="w-full rounded-lg py-2.5 text-sm font-medium disabled:opacity-50"
                style={{ background: "#dba956", color: "#0a0c10" }}
              >
                {status === "loading" ? "Preparing checkout…" : `Subscribe to ${t.name}`}
              </button>
            </div>
          ))}
        </div>

        <div className="rounded-xl border border-[#1e232e] p-5 mb-8" style={{ background: "#0f131a" }}>
          <div className="text-xs font-mono uppercase tracking-wide text-[#8b95a6] mb-3">Checkout details</div>
          <input
            type="email" placeholder="customer email" value={email} onChange={(e) => setEmail(e.target.value)}
            className="w-full rounded-lg border border-[#2a3040] bg-[#0a0c10] px-3 py-2 text-sm mb-3"
          />
          <div className="flex gap-2 mb-3">
            <button onClick={() => setGateway("payu")} className={`text-xs px-3 py-1.5 rounded-full border ${gateway === "payu" ? "border-[#dba956] text-[#dba956]" : "border-[#2a3040] text-[#8b95a6]"}`}>PayU</button>
            <button onClick={() => setGateway("razorpay")} className={`text-xs px-3 py-1.5 rounded-full border ${gateway === "razorpay" ? "border-[#dba956] text-[#dba956]" : "border-[#2a3040] text-[#8b95a6]"}`}>Razorpay</button>
          </div>

          {error && <p className="text-xs text-[#f87171] mb-3">{error}</p>}
          {result?.checkout && typeof result.checkout === "string" && (
            <p className="text-xs text-[#4ade80] mb-3">
              Payment link created: <a href={result.checkout} target="_blank" rel="noreferrer" className="underline">{result.checkout}</a>
            </p>
          )}
          {result?.checkout && typeof result.checkout === "object" && (
            <p className="text-xs text-[#4ade80] mb-3">PayU checkout form prepared (txnid ready) — a real page would auto-submit this to PayU.</p>
          )}
        </div>

        <details className="rounded-xl border border-[#1e232e] p-5" style={{ background: "#0f131a" }}>
          <summary className="text-xs font-mono uppercase tracking-wide text-[#8b95a6] cursor-pointer">
            Founder test mode — merchant credentials (staging only)
          </summary>
          <p className="text-xs text-[#a8b1c2] my-3">
            A real customer never sees this. In production, merchant credentials live server-side (environment
            variables), never in the checkout request from a customer&apos;s browser. This panel exists only so you can
            test the real checkout flow today, on staging, before that server-side config exists.
          </p>
          {gateway === "razorpay" ? (
            <div className="grid grid-cols-2 gap-2">
              <input placeholder="Razorpay Key ID" value={razorpayKeyId} onChange={(e) => setRazorpayKeyId(e.target.value)} className="rounded-lg border border-[#2a3040] bg-[#0a0c10] px-3 py-2 text-xs" />
              <input placeholder="Razorpay Key Secret" type="password" value={razorpaySecret} onChange={(e) => setRazorpaySecret(e.target.value)} className="rounded-lg border border-[#2a3040] bg-[#0a0c10] px-3 py-2 text-xs" />
            </div>
          ) : (
            <div className="grid grid-cols-2 gap-2">
              <input placeholder="PayU Merchant Key" value={payuKey} onChange={(e) => setPayuKey(e.target.value)} className="rounded-lg border border-[#2a3040] bg-[#0a0c10] px-3 py-2 text-xs" />
              <input placeholder="PayU Merchant Salt" type="password" value={payuSalt} onChange={(e) => setPayuSalt(e.target.value)} className="rounded-lg border border-[#2a3040] bg-[#0a0c10] px-3 py-2 text-xs" />
            </div>
          )}
        </details>

        <p className="text-xs text-[#5b6472] mt-8">
          Questions before you pay? Email{" "}
          <a href={`mailto:${SUPPORT_EMAIL}`} className="text-[#dba956] hover:underline">{SUPPORT_EMAIL}</a>
        </p>
      </div>
    </div>
  );
}
